### ISSUE TITLE
Updating algokit cli and scaffolded projects

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-cli#181]
Big kudos to the team for making this cli tool!

Quick question:

What is the options available at the moment to update existing already scaffolded projects to work with newer algokit verison?

For instance, I have a project scaffolded for beaker with algokit 0.2.0, I bump it to 0.3.0 aside from improvements in cli itself is there a way to propagate updates to template related artifacts (vscode tasks and etc)? If yes, what is the best practice?

**Comment by robdmoore** [comment]
Hey!

When you update algokit itself, that doesn't necessarily have any impact on your project - they are decoupled from each other. Algokit the cli tool may have updated functionality, but the underlying libraries and templates that determine what happens when you `algokit init` a new project are separate.

The libraries will be distributed using PyPi (for Python) or npm (for TypeScript, which isn't in there yet, but is coming soon) and so you can use the usual approaches to detect and receive updates for those libraries.

The template structure itself may change and for the moment you can't receive any updates to the structure, but one of the things we will expose at some point is the ability to update your structure too. This would cover things like vs code setup etc. Largely though, I'd say these things rarely need to change and if it's all working for you then it's probably fine.
