### ISSUE TITLE
Migrate to official algorand docker images for algod and indexer once available

### ISSUE THREAD

**Issue by ghost** [algorandfoundation/algokit-cli#230]
## Status

Docker Images

* makerxau/algorand-indexer-dev:latest
* makerxau/algorand-sandbox-dev:latest

https://hub.docker.com/u/makerxau

## Expected

Docker Images

* algorand/algorand-indexer-dev:latest
* algorand/algorand-sandbox-dev:latest

https://hub.docker.com/u/algorand

## Possible Workaround

Docker Images

* algokit/algorand-indexer-dev:latest
* algokit/algorand-sandbox-dev:latest

https://hub.docker.com/u/algokit

**Comment by robdmoore** [comment]
The intention is to use the official algorand images. They weren’t ready until recently (and still might not be, I need to go back and test) with the functionality needed for the Algokit experience.

in the meantime, the MakerX images are being used as a stopgap since they provide the desired experience and are maintained by a trusted source: https://github.com/MakerXStudio/algorand-sandbox-dev

**Comment by abebeos** [comment]
Production companies should be neutral. I do not like it to see "makerx" when I use Algorand.

Consider at least the workaround to use "algokit".

**Comment by robdmoore** [comment]
I believe the Algorand official images are likely ready after consulting with the team behind them. We'll try and switch over and see if it still all works OK.

**Comment by scholtz** [comment]
they are not even versioned.. https://hub.docker.com/r/makerxau/algorand-indexer-dev/tags

this is versioned https://hub.docker.com/r/scholtz2/algorand-indexer/tags

building from https://github.com/scholtz/AlgorandNodes/tree/main/docker

algorand official images are running under root, thats why i had to make these images, so that it can run in non rooted environment.. 

why is makerx getting all the business from the foundation and they do not deliver good products?

**Comment by abebeos** [comment]
> why is makerx getting all the business from the foundation and they do not deliver good products?

nobody really cares @ Algorand inc/org

**Comment by abebeos** [comment]
@scholtz , see additionally the currently open issues to understand "nobody cares":

https://github.com/algorandfoundation/algokit-cli/issues

**Comment by Loedn** [comment]
We're using MakerX's indexer because there still isn't an official Indexer image from inc. From when this issue was opened we have migrated to the official sandbox and have been using it.

**Comment by achidlow** [comment]
A bit of history here in case anyone is interested how this came about. 

A long, long time ago (well, over a year ago at least), before AlgoKit was even a twinkle in the eye of John Woods, there was only sandbox.sh. This worked well for local development and was very flexible, but it added enormous time to CI/CD pipelines, including those of some internal projects at MakerX. In order to speed things up, I quickly extracted the key parts of sandbox.sh and made a pipeline to build these images in Azure DevOps on our internal infrastructure. (We even helped fix some indexer devmode issues along the way https://github.com/algorand/indexer/pull/920.) It did everything we needed - in particular, versioning wasn’t required as we always wanted latest - and also, it cross compiled and built both x86 and ARM images since a lot of our team uses Apple Silicon MacBooks and the Docker x86 emulation was extremely slow back then.  This worked well enough for us that we decided to make them public in case anyone else found a use in them. 

Fast forward many months, and at the beginning of the AlgoKit project, there was discussion amongst the whole AlgoKit team (not just MakerX) as to the best path forward. It was decided to use the MakerX images for now, and that Algorand Inc would make official images, so it didn’t make sense to invest in updating the MakerX ones. We now have official images for algod, and placed these in AlgoKit as soon as possible. We will do the same once the official indexer image is available.

**Comment by abebeos** [comment]
Justifications, instead of simply sticking to a MUST Requirement.

**Comment by robdmoore** [comment]
algokit 1.7.0 now has only official images. See #351.
