### ISSUE TITLE
Change the README to be more Code/Project Oriented

### ISSUE THREAD

**Issue by abebeos** [algorandfoundation/algokit-cli#246]
### Code and Work on it

This is a code repository.

The README should be mostly about the code and working ON this code:

- How to build this code 
- How to run the algokit build
- What other subsystems exist
- How to contribute
- How to setup a core-dev-environment to work on(!) algokit-cli

First attempt towards this was:

- https://github.com/algorandfoundation/algokit-cli/pull/240

But this failed.

### Not about the Product

The README should not be about the Product, this can be described in the User-Manual (or "Developer Manual").

**Comment by robdmoore** [comment]
Hi @abebeos,

Thanks for the feedback.

We point users readily to the README.md of this repository as the starting point for using AlgoKit. It has a lot of useful context about what AlgoKit is and point to the various components and documentation etc.

This pattern is pretty common across the industry in my experience, I think most root README.md files are targetted towards usage rather than contribution, a few examples I just randomly looked at to confirm this:

* [React](https://github.com/facebook/react)
* [TypeScript](https://github.com/microsoft/TypeScript)
* [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts)
* [Google Test Rust](https://github.com/google/googletest-rust)

All of them have a very similar structure to AlgoKit with an initial description, installation and usage instructions and then a section point to how to contribute that links off to another file.

In our case we have a [How can I contribute](https://github.com/algorandfoundation/algokit-cli#how-can-i-contribute) section on the README that links to [CONTRIBUTING.md](https://github.com/algorandfoundation/algokit-cli/blob/main/CONTRIBUTING.md) that has reasonable coverage (definitely happy to take contributions to that file to add more detail though if you have any feedback on it.

**Comment by abebeos** [comment]
again "comment & close".

Very well, seems you've everything totally under control.

(just know this: Code Repositories need to focus on Core-Development, this is a simple logical fact that no Meta, Google, MS and other "arrogant to the bones" giants can change. Usage is handled in the user/developer manuals. Luckily there are hundreds of projects that follow this).
