### ISSUE TITLE
README.md refers to non-existant algokit command 

### ISSUE THREAD

**Issue by HashMapsData2Value** [algorandfoundation/algokit-cli#317]
![image](https://github.com/algorandfoundation/algokit-cli/assets/83883690/f8e01531-26de-4f6e-9f75-9ec6446313d2)

The README.md that gets generated under project/backend/smart_contracts instructs that you should run `algokit generate smart-contract` at the root of the repository. However, there is no `algokit generate smart-contract` command, only `algokit generate client`. 

![image](https://github.com/algorandfoundation/algokit-cli/assets/83883690/2055b04d-c4f1-41e3-9b6d-e9996f779096)

**Comment by aorumbayev** [comment]
Hello @HashMapsData2Value thanks for reporting, i believe this is a non-issue. 

Please refer to [using-custom-generate-commands](https://github.com/algorandfoundation/algokit-cli/blob/main/docs/features/generate.md#2-using-custom-generate-commands) documentation to read more about how exactly generate works when dealing with custom generators (`smart-contracts` in your case). I see that you have an `.algokit` folder in your template, this is actually the custom generator that comes bundles with the beaker template and when you run algokit generate from the root of the backend folder (the same level that contains algokit.toml file) then this custom `smart-contract` generator command is injected into algokit dynamically. You can also inspect algokit.toml to see how exactly it references the custom generator. 

So I suspect the issue is due to the fact that you may be running this command from the wrong folder, keep in mind if this is within a fullstack template then backend and frontend folders are completely independent so READMEs inside those folders refer exclusively to their own scope. 

Please confirm the version of algokit you are using and try re running the generate from the root of the backend folder. 

Lastly, if you are interested in creating your own custom generators (which are essentially, mini jinja templates that allow you to customize a lot of options in regards to any file manipulation you might need in your algokit project, you can also execute custom scripts in any language for pre or post processing) -> https://github.com/algorandfoundation/algokit-cli/blob/main/docs/tutorials/algokit-template.md#working-with-generators.
